### ISSUE TITLE
Repos won't expand to display their content after some filter criteria like "help wanted" is selected

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mozwebqa-dashboard#64] opened 2016-07-20 05:30 UTC
Steps to Reproduce:
1. Load mozilla.github.io/mozwebqa-dashboard/
2. Click on Issues (http://mozilla.github.io/mozwebqa-dashboard/#/issues), and then choose a filter criteria, such as "help wanted"
3. Notice that the displayed repos collapse

Now try to expand them; the "twisty" to their left changes its orientation, but the repo never expands to shows its content.

**Comment by davehunt** [comment] 2016-07-20 09:33
Duplicate of https://github.com/mozilla/mozwebqa-dashboard/issues/50 - there are currently no issues with the "help wanted" label.

**Closed as completed by davehunt** 2016-07-20 09:33 UTC
Labels: bug
